from __future__ import annotations

from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "apps" / "web" / "src" / "lib" / "generated" / "capability-registry.ts"
sys.path.insert(0, str(ROOT / "packages" / "database" / "src"))

from labelos_database.capabilities import CAPABILITY_REGISTRY  # noqa: E402


def _camel_case(identifier: str) -> str:
    parts = identifier.replace(".", "_").split("_")
    return parts[0] + "".join(part.capitalize() for part in parts[1:])


def _quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    capability_entries = [
        f"  {_camel_case(definition.key)}: {_quote(definition.key)},"
        for definition in CAPABILITY_REGISTRY
    ]
    registry_entries = [
        "\n".join(
            [
                "  {",
                f"    key: capabilities.{_camel_case(definition.key)},",
                f"    displayName: {_quote(definition.display_name)},",
                f"    description: {_quote(definition.description)},",
                "    systemCapability: true,",
                "  },",
            ]
        )
        for definition in CAPABILITY_REGISTRY
    ]

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        "\n".join(
            [
                "/* eslint-disable */",
                "// This file is generated by scripts/generate-capability-registry.py.",
                "// Do not edit by hand.",
                "",
                "export const capabilityIdentifierPattern = /^[a-z][a-z0-9_]*(?:\\.[a-z][a-z0-9_]*)+$/;",
                "",
                "export const capabilities = {",
                *capability_entries,
                "} as const;",
                "",
                "export type Capability = (typeof capabilities)[keyof typeof capabilities];",
                "",
                "export type CapabilityDefinition = {",
                "  key: Capability;",
                "  displayName: string;",
                "  description: string;",
                "  systemCapability: true;",
                "};",
                "",
                "export const capabilityRegistry: readonly CapabilityDefinition[] = [",
                *registry_entries,
                "] as const;",
                "",
            ]
        ),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
