"""Generate scheduling client contracts from the public FastAPI OpenAPI schema.

Run from any directory; --check fails if the checked-in client has drifted.
No database, credentials, server process or new npm dependency is needed.
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "apps/api/src"), str(ROOT / "packages/database/src")]

from fastapi import FastAPI  # noqa: E402

from labelos_api.api.v1.scheduling import router  # noqa: E402

OUTPUT = ROOT / "apps/web/src/lib/generated/scheduling-api.ts"


def ts_type(schema):
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(ts_type(branch) for branch in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema['items'])}>"
    if kind == "object":
        fields = schema.get("properties", {})
        if not fields:
            return (
                "Record<string, never>"
                if schema.get("additionalProperties") is False
                else "Record<string, unknown>"
            )
        required = schema.get("required", [])
        return (
            "{\n"
            + "\n".join(
                f"  {json.dumps(name)}{'' if name in required else '?'}: {ts_type(field)};"
                for name, field in fields.items()
            )
            + "\n}"
        )
    primitives = {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }
    if kind in primitives:
        return primitives[kind]
    raise ValueError(f"Unsupported scheduling schema: {schema}")


def generated_source():
    app = FastAPI()
    app.include_router(router, prefix="/api/v1")
    schema = app.openapi()
    lines = [
        "// Generated by scripts/generate-scheduling-client.py. Do not edit.",
        "// UUIDs and timezone-aware instants are strings on the wire.",
        "",
    ]
    for name, definition in sorted(schema["components"]["schemas"].items()):
        lines += [
            "// prettier-ignore",
            f"export type {name} = {ts_type(definition)};",
            "",
        ]
    lines += ["// prettier-ignore", "export type SchedulingApi = {"]
    for path, methods in sorted(schema["paths"].items()):
        lines.append(f"  {json.dumps(path)}: {{")
        for method, operation in methods.items():
            lines.append(f"    {method}: {{")
            for location in ("path", "query", "header"):
                params = [
                    p for p in operation.get("parameters", []) if p["in"] == location
                ]
                if params:
                    definition = {
                        "type": "object",
                        "properties": {p["name"]: p["schema"] for p in params},
                        "required": [p["name"] for p in params if p.get("required")],
                    }
                    lines.append(f"      {location}: {ts_type(definition)};")
            if "requestBody" in operation:
                body = operation["requestBody"]["content"]["application/json"]["schema"]
                lines.append(f"      body: {ts_type(body)};")
            lines.append("      responses: {")
            for status, response in sorted(operation["responses"].items()):
                body = (
                    response.get("content", {})
                    .get("application/json", {})
                    .get("schema")
                )
                if body:
                    lines.append(f"        {status}: {ts_type(body)};")
            lines += ["      };", "    };"]
        lines.append("  };")
    lines += ["};", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = generated_source()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != source:
            raise SystemExit(
                "Scheduling client types are stale; run python scripts/generate-scheduling-client.py"
            )
    else:
        OUTPUT.write_text(source, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
